<?php require('header.php') ?>

    <!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">
            <h1 class="display-3">A Warm Welcome!</h1>
            <p class="lead">This website was created for those who have selling and buying television sets in mind .Please use this service wisely and don't in any dubious activity on it.Thank you very much.</p>
            <a href="viewAd.php" class="btn btn-primary btn-lg">Browse Ads</a>
        </header>

        <!-- Page Features -->


        <!-- /.container -->
    </div>
<?php require('template/footer.phtml')?>