<?php require('header.php') ?>


    <div class="flipeffect" >
        <div class="col-md-4" style="margin-left:auto;margin-right:auto;margin-top:auto;">
            <form method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>" accept-charset="UTF-8" role="form" id="loginform" class="form-signin">
                <fieldset>
                    <h2 class="text-center">LOG IN</h2>
                    <?php if (isset($view->error)) : ?> <!-- displays an error message if the entered information are wrong -->
                        <div class="alert alert-danger">
                            <a href="login.php" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong><?php echo $view->error?></strong>
                        </div>
                    <?php endif?>
                    <div class="form-group">
                        <input class="form-control" placeholder="E-mail" name="email" type="text" size = 64 required= "required">
                    </div>
                    <div class="form-group">

                        <input class="form-control" placeholder="Password" name="password" type="password" value="" required= "required">
                    </div>
                    <div class="form-group">
                        <input class="btn btn-default btn-block" type="submit" name="login" value="Log in">
                    </div>
                </fieldset>
            </form>
        </div>
    </div>



<?php require('template/footer.phtml') ?>