<?php require('header.php') ?>


<body>
<div class="container">
<h2>Start typing in the input field below:</h2>
<div class="col-lg-12">
<form>
    <div class="form-group">
     <label for="search">Search:</label>
    <input type="text" class="form-control" onkeyup="showHint(this.value)">
    </div>
</form>
</div>

<script src="../js/Ajax.js">
</script>

<p>Suggestions: <span id="txtHint"></span></p>

<div id="results">

</div>


<div id="searchResults">

</div>
</div>
    
</body>



<?php require('template/footer.phtml') ?>