<?php require('header.php') ?>

    <?php foreach ($view->advertDataSet as $advertData) {
       // if ($today->format('Y-m-d') < $advertData->getExpiryDate()) { //Checks if the current date is still less than expiry date
            if (isset($_SESSION["name"])) {
                if ($headerView->account->getAdminStatus() == "T") {
                    echo
                        '<div class="card" style="width:280px">' .
                        ' <div class="card-header">' . $advertData->getTitle() . '</div> <!-- header -->' .
                        '<img src="images/' . $advertData->getImage() . '" class="card-img-top"  alt="' . $advertData->getTitle() . '">' .
                        '<div class="card-body"><p><strong>TV Type : </strong>' . $advertData->getAdType() . '</p>' .
                       // '<p><strong>Ad Description : </strong>' . $advertData->getDescription() . '</p>' .
                        '<p><strong>Expires on : </strong>' . $advertData->getExpiryDate() . '</p>' .
                        '<p><strong>Price : </strong>£' . $advertData->getPrice() . '</p>' .
                        '<p>Item price is <strong>' . $advertData->getAdStatus() . '</strong></p>' .
                        '<div class="btn-group">' .
                        '<a href="viewAd.php?id='. $advertData->getId().'"  class="btn btn-outline-secondary btn-sm">Add to Watchlist</a> <!-- Add to Watchlist HERE -->' .
                        '<a href="mailto:' . $advertData->getEmail() . '" target="_blank" class="btn btn-outline-secondary btn-sm btn-sm">Contact Seller</a> <!-- Contact Seller HERE -->' .
                        '<a href="viewAd.php?delete_id='. $advertData->getId().'"  class="btn btn-outline-danger btn-sm">Delete Ad</a> <!-- Delete Ad HERE --></div></div>
                        </div>';
                }
                else{
                    echo
                        '<div class="card" style="width:280px">' .
                        ' <div class="card-header">' . $advertData->getTitle() . '</div> <!-- header -->' .
                        '<img src="images/' . $advertData->getImage() . '" class="card-img-top"  alt="' . $advertData->getTitle() . '">' .
                        '<div class="card-body"><p><strong>TV Type : </strong>' . $advertData->getAdType() . '</p>' .
                        '<p><strong>Ad Description : </strong>' . $advertData->getDescription() . '</p>' .
                        '<p><strong>Expires on : </strong>' . $advertData->getExpiryDate() . '</p>' .
                        '<p><strong>Price : </strong>£' . $advertData->getPrice() . '</p>' .
                        '<p>Item price is <strong>' . $advertData->getAdStatus() . '</strong></p>' .
                        '<div class="btn-group">' .
                        '<a href="viewAd.php?id='. $advertData->getId().'"  class="btn btn-outline-secondary btn-sm">Add to Watchlist</a> <!-- Add to Watchlist HERE -->' .
                        '<a href="mailto:' . $advertData->getEmail() . '" target="_blank" class="btn btn-outline-secondary btn-sm">Contact Seller</a> <!-- Contact Seller HERE -->' .
                        '</div></div>
                        </div>';
                }
            }
            elseif(!isset($_SESSION["name"]))// Prevents people who are not logged in from viewing information
                {
                    echo
                         '<div class="card text-center">' .
                        ' <div class="card-header">' . $advertData->getTitle() . '</div> <!-- header -->' .
                        '<img src="images/' . $advertData->getImage() . '" class="card-img-top"  style="width:auto;max-height:220px;" alt="' . $advertData->getTitle() . '">' .
                        '<div class="card-body"><p><strong>TV Type : </strong>' . $advertData->getAdType() . '</p>' .
                        '<h3><i><strong>You need to be logged in to continue </strong></i></h3></div>
                        </div>';

            }
        //}

    //    elseif($today->format('Y-m-d') > $advertData->getExpiryDate()){
      //      $advertDataSet->deleteExpiredAd($today->format('Y-m-d'));   //Calls a method that deletes the ad
     //   }
    }?>
         


<?php require('template/footer.phtml') ?>
