<?php require('header.php') ?>

<div class="container-fluid">

            <div class="row">
        
                <form role="form" action="<?php echo $_SERVER['PHP_SELF'];?>" method="post">

                    <div class="row">
                        <div class="form-group col-lg-6 col-md-6 col-sm-12">
                    <input class="form-control" type="text" name="title" placeholder="Enter your Search here"/></div>
                        <div class="form-group col-lg-6 col-md-6 col-sm-12">
                        <input class="btn btn-default" type="submit" name="searchButton" value="Search"></div>
                    </div>
                    </form>
               
                       <div class="col-md-6 dropdown">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Sort</button>
      <div class="dropdown-menu">
            <a href="../viewAd.php?sort=name(A-Z)" class="dropdown-item">Title A to Z</a>
            <a href="../viewAd.php?sort=name(Z-A)" class="dropdown-item">Title Z to A</a>
            <a href="../viewAd.php?sort=negotiable" class="dropdown-item">Is negotiable</a>
            <a href="../viewAd.php?sort=nonnegotiable" class="dropdown-item">Is Non-negotiable</a>
            <a href="../viewAd.php?sort=priceAsc" class="dropdown-item">Lowest priced first</a>
            <a href="../viewAd.php?sort=priceDesc" class="dropdown-item">Highest priced first</a>
                          </div>
            </div>
                
        </div>
    <div class="card-deck">

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">

    <?php foreach ($view->advertDataSet as $advertData) {
       // if ($today->format('Y-m-d') < $advertData->getExpiryDate()) { //Checks if the current date is still less than expiry date
            if (isset($_SESSION["name"])) {
                if ($headerView->account->getAdminStatus() == "T") {
                    echo
                        '<div class="card">' .
                        ' <div class="card-header">' . $advertData->getTitle() . '</div> <!-- header -->' .
                        '<img src="images/' . $advertData->getImage() . '" class="card-img-top"  style="width:auto;max-height:220px;" alt="' . $advertData->getTitle() . '">' .
                        '<div class="card-body"><p><strong>TV Type : </strong>' . $advertData->getAdType() . '</p>' .
//                        '<p><strong>Ad Description : </strong>' . $advertData->getDescription() . '</p>' .
                        '<p><strong>Expires on : </strong>' . $advertData->getExpiryDate() . '</p>' .
                        '<p><strong>Price : </strong>£' . $advertData->getPrice() . '</p>' .
                        '<p>Item price is <strong>' . $advertData->getAdStatus() . '</strong></p>' .
                        '<div class="btn-group">' .
                        '<a href="viewAd.php?id='. $advertData->getId().'"  class=" btn btn-outline-secondary btn-sm">Watchlist +</a> <!-- Add to Watchlist HERE -->' .
                        '<a href="mailto:' . $advertData->getEmail() . '" target="_blank" class=" btn btn-outline-secondary btn-sm">Contact Seller</a> <!-- Contact Seller HERE -->' .
                        '<a href="viewAdvert.php?id='. $advertData->getId().'"  class=" btn btn-outline-secondary btn-sm">View</a>'.
                        '<a href="viewAd.php?delete_id='. $advertData->getId().'"  class=" btn btn-outline-danger btn-sm">Delete</a> <!-- Delete Ad HERE --></div></div>
                        </div>';
                }
                else{
                    echo
                         '<div class="card text-center">' .
                        ' <div class="card-header">' . $advertData->getTitle() . '</div> <!-- header -->' .
                        '<img src="images/' . $advertData->getImage() . '" class="card-img-top"  style="width:auto;max-height:220px;" alt="' . $advertData->getTitle() . '">' .
                        '<div class="card-body"><p><strong>TV Type : </strong>' . $advertData->getAdType() . '</p>' .
                        '<p><strong>Expires on : </strong>' . $advertData->getExpiryDate() . '</p>' .
                        '<p><strong>Price : </strong>£' . $advertData->getPrice() . '</p>' .
                        '<p>Item price is <strong>' . $advertData->getAdStatus() . '</strong></p>' .
                        '<div class="btn-group">' .
                        '<a href="viewAd.php?id='. $advertData->getId().'"  class=" btn btn-outline-secondary btn-sm">Watchlist +</a> <!-- Add to Watchlist HERE -->' .
                        '<a href="viewAdvert.php?id='. $advertData->getId().'"  class=" btn btn-outline-secondary btn-sm">View Ad</a>'.
                        '<a href="mailto:' . $advertData->getEmail() . '" target="_blank" class=" btn btn-outline-secondary btn-sm">Contact Seller</a> <!-- Contact Seller HERE -->' .
                        '</div></div>
                        </div>';
                }
            }
            elseif(!isset($_SESSION["name"]))// Prevents people who are not logged in from viewing information
                {
                

                    echo
                     '<div class="card text-center">' .
                        ' <div class="card-header">' . $advertData->getTitle() . '</div> <!-- header -->' .
                        '<img src="images/' . $advertData->getImage() . '" class="card-img-top"  style="width:auto;max-height:220px;" alt="' . $advertData->getTitle() . '">' .
                        '<div class="card-body"><p><strong>TV Type : </strong>' . $advertData->getAdType() . '</p>' .
                        '<h3><i><strong>You need to be logged in to continue </strong></i></h3></div>
                        </div>';

            }
        //}

    //    elseif($today->format('Y-m-d') > $advertData->getExpiryDate()){
      //      $advertDataSet->deleteExpiredAd($today->format('Y-m-d'));   //Calls a method that deletes the ad
     //   }
    }?>
            </form>
               </div>


<?php require('template/footer.phtml') ?>
